apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: portal-template
  title: Portal Template
  description: Create a new portal project
  tags:
    - gridsome
    - vue
    
spec:
  owner: rdev_portal
  templater: cookiecutter
  type: website
  path: '.'
